gadget-inc/mobx-quick-tree

- spec/model.spec.ts
- src/errors.ts
- src/model.ts
This allows us to optimize model instantiation, because we can create a prototype for the actions instead of having to call the action initializer on every instantiation.
Verified this passes in Gadget's CI suite, after we made some changes to no longer need actions in our read-only codepaths.
> Make actions throw by default.

- package.json
- spec/model.spec.ts
- spec/simple.spec.ts
- src/api.ts
- src/array.ts
- src/enumeration.ts
- src/map.ts
This previously didn't work:
```typescript
const values = ["a", "b", "c"] as const;
const MyEnum = types.enumeration(values);
```
We don't mutate this array, so it can be readonly. This allows people to use `as const` on an array and be able to use that as an input to enumeration without special casts or clones, which I think is desirable. This PR corrects the issue.
Also in this PR is a version lock for TypeScript (and bumped all other `devDependencies`). Since we don't have a `yarn.lock` in this repo, we take the latest version that matches the specifier. One of the 4.8 versions was spitting out this error:
```
TypeError: host.fileExists is not a function
```
I had a to make a few other changes to be able to make this happen, far more than the main change in this PR 🙈
> Allow readonly/const arrays for types.enumeration

- package.json
The current version seems to be building broken typescript. Specifically, the error I'm seeing is
```
node_modules/mobx-quick-tree/dist/src/index.d.ts:15:250 - error TS1005: '?' expected.
```
And that line refers to the generated type for `types.compose`, which is quite
large. Although I tested this and it seemed to work, I must have not been using
the built version locally.
I'll unpublish 0.3.1. Even with the version currently specified (4.7.4) the file was considered ill-formatted. Really bizarre 😕
> Revert typescript bump.

- spec/api.spec.ts
- spec/map.spec.ts
- src/map.ts
- src/snapshot.ts
1. When using a frozen type in a map, there can be a key/value pair where the value can be null and hence cannot be indexed for an identifier. MST always uses the key from the snapshot as the key in the map, so we now do the same.
2. Safe references can be undefined, so we shouldn't try to index it for an identifier when creating a snapshot.
> Fix two bugs with identifiers

- spec/api.spec.ts
- spec/class-model.spec.ts
- spec/fixtures/OptionalClassModel.ts
- spec/getSnapshot.spec.ts
- spec/maybe.spec.ts
- spec/simple.spec.ts
- src/api.ts
- src/snapshot.ts
- src/types.ts
This fixes a big issue after adding class models where ITypes wrapping class models didn't correctly instantiate. It all stems from IStateTreeNode -- the existing types use it to decorate any ole object with the `$type` it is of. This facilitates grabbing the type at runtime for API functions like `getType`, and for grabbing the type at type time to power type safety in the API for things like `getSnapshot` etc.
IStateTreeNode is thusly key, and it used to be that everything that was intantiated could be wrapped in an `IStateTreeNode` wrapper pretty easily. We need to keep doing this for IMaybeType and IReferenceType and the other ITypes which wrap some other inner type, but we don't want to do it to class models, which define their own `$type` property, and break things if extended with …
> Fix typescript types for snapshotting optional types

- README.md
- spec/class-model.spec.ts
- src/api.ts
- src/class-model.ts
We have a few volatile properties Gadget-side that we set after instantiation. The setters for these props work like any others: we decorate the setter with `@action` so that it can mess with stuff and is present on both the observable and readonly instance type. Because this setter is a normal action, we are forced to use observable instances of these objects. In some cases, this is a big performance penalty -- the *only* prop we want to ever change is a volatile one, and the snapshot bit really is readonly. So, I think we should introduce an escape hatch for "i know what I am doing", and allow a select few actions to actually be invoked on readonly instances.
The rule I propose is that these actions are only allowed to muck with volatiles. Volatiles are for the weird, not-snapshot, …
> Add a facility for running actions that only touch volatiles on readonly instances

- spec/simple.spec.ts
- spec/union.spec.ts
- src/class-model.ts
- src/errors.ts
- src/optional.ts
- src/simple.ts
- src/union.ts
Gadget side, we instantiate a lot of unions that have many elements. Both MQT (or MST) have to take an incoming snapshot and figure out which element of the union is the right one to instantiate and return for the union. Both of them have a pretty naive algorithm for doing this: take each element and check the snapshot against it, returning the first union element which does. This means a LOT of `type.is` checks, where each type in the union is compared against the snapshot. These type.is checks basically do a full instantiation under the hood -- there's no fancy fast path for `.is` for a lot of types, there's just running the runtime code that would boot an instance, and seeing if it fails.
This works in the general case but has gotten really slow in Gadget, specifically for the …
> Allow union type instantiation to be faster by specifying a discriminator property

- spec/api.spec.ts
- src/array.ts
- src/base.ts
- src/class-model.ts
- src/custom.ts
- src/enumeration.ts
- src/frozen.ts
- src/late.ts
- src/map.ts
- src/maybe.ts
- src/model.ts
- src/optional.ts
- src/reference.ts
- src/refinement.ts
- src/simple.ts
- src/types.ts
- src/union.ts
This improves the raw speed that MQT can create read-only instances a lot! I did some profiling with a new benchmark that really stresses class model, map, and array creation, and it showed that a huge amount of time was being spent in the `Object.defineProperty` and `Reflect.defineProperty` calls that we make to track our internal state, like the environment, the parent, and the type of each object. For each of those three, I tried to come up with different strategies that didn't require these slow property setters.
The results are good!
On `main`:
```
❯ p x bench/create-large-root.ts
> @gadgetinc/mobx-quick-tree@0.4.0 x /Users/airhorns/Code/mobx-quick-tree
> ts-node --transpile-only "bench/create-large-root.ts"
instantiating a large root x 395 ops/sec ±0.88% (90 runs sampled)
```
On …
> Faster instantiation

- src/class-model.ts
- src/fast-instantiator.ts
- src/map.ts
- src/optional.ts
- src/reference.ts
- src/types.ts
I was curious about how hard and how effective the "compile a function that does the same thing but with loops unrolled and indirection removed" approach would be for model instantiation. I tried it. It works ... really well.
On `main`:
```
❯ p x bench/create-large-root.ts
> @gadgetinc/mobx-quick-tree@0.4.0 x /Users/airhorns/Code/mobx-quick-tree
> ts-node --transpile-only "bench/create-large-root.ts"
instantiating a large root x 395 ops/sec ±0.88% (90 runs sampled)
```
On the first pass optimization branch in #44:
```
❯ p x bench/create-large-root.ts
> @gadgetinc/mobx-quick-tree@0.4.0 x /Users/airhorns/Code/mobx-quick-tree
> ts-node --transpile-only "bench/create-large-root.ts"
instantiating a large root x 925 ops/sec ±1.01% (88 runs sampled)
```
On this branch:
```
❯ p x …
```
> Putting the quick in quick tree: compile an instantiation function for each class model type

- spec/fixtures/FruitAisle.ts
- src/class-model.ts
- src/fast-instantiator.ts
- src/late.ts
Before, we reverted to the slow path instantiation for all late types which is a bit of a fail -- if it was a plain old optional type or similar within the late, we'd skip the fast path completely. Instead, if we build the instantiator late, we can shuck the late wrapper around the actual type, and use fast path instantiation for the type if available.
On main with a lazy type on the fruit aisle:
```
❯ p x bench/all.ts
> @gadgetinc/mobx-quick-tree@0.4.0 x /Users/airhorns/Code/mobx-quick-tree
> ts-node --transpile-only "bench/all.ts"
instantiating a small root x 906,528 ops/sec ±0.59% (88 runs sampled)
instantiating a large root x 2,860 ops/sec ±3.27% (89 runs sampled)
instantiating a large union x 168,566 ops/sec ±1.40% (91 runs sampled)
```
On this branch:
```
> …
```
> Fast instantiation through lazy types

- src/api.ts
Needed this for some work I'm doing and saw it wasn't there, so let's export it 🚀 
For the time being, I'm going to implement it myself, since it's a pretty simple transform, but thought it would be good to include it for moving forward.
> Export unescapeJsonPath from mobx-state-tree

- .eslintrc.js
- jest.config.js
- package.json
- pnpm-lock.yaml
- spec/jest.setup.ts
- spec/schemaHash.spec.ts
- src/array.ts
- src/base.ts
- src/class-model.ts
- src/custom.ts
- src/enumeration.ts
- src/frozen.ts
- src/late.ts
- src/map.ts
- src/maybe.ts
- src/model.ts
- src/optional.ts
- src/reference.ts
- src/refinement.ts
- src/simple.ts
- src/types.ts
- src/union.ts
- src/utils.ts
This adds a new function to the MQT types that derives a stable hash of the type for use in cache keys. The hash changes when the constituent snapshots change shape, but is stable otherwise, across processes, symbol renames, etc.
We wanna use this for building cache keys Gadget side that expire when the schema changes.
> Add a hashing function to all types for deriving cache keys from

- src/class-model.ts
- src/fast-instantiator.ts
- src/symbols.ts
- src/types.ts
On top of https://github.com/gadget-inc/mobx-quick-tree/pull/65
15% improvement by removing a megamorphic call to the fast instantiator function! Yeesh!
On `perf-improvements`:
```
❯ node dist/bench/create-many-different-roots.js
instantiating a large root x 3,258 ops/sec ±0.84% (100 runs sampled)
instantiating a small root x 10,573,575 ops/sec ±0.21% (92 runs sampled)
instantiating a diverse root x 464,002 ops/sec ±0.15% (100 runs sampled)
```
On this branch:
```
❯ node dist/bench/create-many-different-roots.js
instantiating a large root x 3,851 ops/sec ±0.29% (97 runs sampled)
instantiating a small root x 15,595,988 ops/sec ±0.46% (99 runs sampled)
instantiating a diverse root x 582,571 ops/sec ±0.65% (99 runs sampled)
```
> Faster constructor 

- .envrc
- .github/actions/setup-test-env/action.yml
- .gitignore
- Benchmarking.md
- flake.lock
- flake.nix
- src/class-model.ts
- src/fast-instantiator.ts
- src/symbols.ts
- src/types.ts
So we're all using the same version when comparing benchmarks. Regrettably, there's a huge performance regression on newer nodes! I am going to work on that next, but at least with a nix setup we're comparing apples to apples.
```
❯ node --version
v21.1.0
❯ p x bench/create-many-different-roots.ts
> @gadgetinc/mobx-quick-tree@0.4.4 x /Users/airhorns/Code/mobx-quick-tree
> ts-node --transpile-only "bench/create-many-different-roots.ts"
instantiating a large root x 3,047 ops/sec ±1.32% (99 runs sampled)
instantiating a small root x 11,136,120 ops/sec ±0.47% (100 runs sampled)
instantiating a diverse root x 449,239 ops/sec ±0.16% (98 runs sampled)
```
```
❯ node --version
v20.9.0
❯ p x bench/create-many-different-roots.ts
> @gadgetinc/mobx-quick-tree@0.4.4 x …
```
> Add nix and upgrade node

- package.json
- pnpm-lock.yaml
- src/enumeration.ts
I want to get the faster constructor patch into Gadget, as well as upgrade MST separately from #69. This PR would cut a new release of MQT with the newest MST and the faster constructor logic. No changes to the supported node version, so we shouldn't notice any regression in Gadget (yet).
Some small perf wins in MST 5.3.0 for the observable side too!
Gadget side integration PR: https://github.com/gadget-inc/gadget/pull/8915
> Upgrade mobx-state-tree version

- src/class-model.ts
- src/fast-instantiator.ts
The VScode Deopt explorer showed that `.createReadOnly` inside the class model `register` function was getting deoptimized because it closes over too-wide a variety of `klass` variable references. We're closing over it so it is correct, but to v8, the callsite is still the same I guess, so it has to deoptimize to pull the right value for the closure! Same for .is and .instantiate -- these dynamically produced functions make a huge difference if they are re-eval'd for each class instead of defined dynamically.
Removing this deoptimization recovered a lot of the node 18 => node 21 performance gap for me! Not all of it. It also makes node 18 faster, but not by nearly as much.
On main on node 18
```
instantiating a small root x 3,105,456 ops/sec ±0.15% (100 runs sampled)
instantiating a large …
```
> Generate a monomorphic version of `.createReadOnly` and `.instantiate` for each class model

- src/fast-instantiator.ts
This makes stack traces and some profiling tools aware of the filename of the eval'd code. In jest, errors now look like this:
```
● clas model references › safe references are equal to the instances they refer to
whatever
at new Root (mqt-eval/dynamic/Root.js:51:17)
at Function.createReadOnly (mqt-eval/dynamic/Root.js:22:28)
at createReadOnly (spec/helpers.ts:6:17)
at Object.<anonymous> (spec/class-model-references.spec.ts:148:24)
```
Flamegraph sadly didn't pick this up but maybe some other tools will -- may as well set it?
Woop woop!
> Add a sourceURL to eval'd code so sourcemap aware things pick up the dynamic function name

- spec/class-model.spec.ts
- src/fast-instantiator.ts
Dates are considered "directly assignable", but they do support numbers as an input value, meaning they're not _really_ directly assignable. This was an issue for optional types, which assumed that the incoming snapshot was good to directly assign, if it wasn't one of the "undefined" values.
This PR fixes that by using the existing `expressionForDirectlyAssignableType` helper for assigning values that are considered directly assignable.
🎩 ✅ Verified the test fails before (for the number case) and passes after.
> Fix read-only instantiation bug with optional date instances on class models

- package.json
Fixes a bug when creating instances of class models that have optional date properties (specifically, when the date property snapshot is not a `Date` instance)
> Release 0.6.2

- spec/api.spec.ts
- src/api.ts
- src/array.ts
- src/base.ts
- src/class-model.ts
- src/custom.ts
- src/enumeration.ts
- src/fast-instantiator.ts
- src/frozen.ts
- src/late.ts
- src/map.ts
- src/maybe.ts
- src/model.ts
- src/optional.ts
- src/reference.ts
- src/refinement.ts
- src/simple.ts
- src/symbols.ts
- src/types.ts
- src/union.ts
Got a `not yet implemented` gadget side when going to use this API, figured it wasn't too hard! We implement by keeping the identifier cache around beyond just after we instantiate, instead of only capturing a reference to the env from that context.
> Implement `resolveIdentifier` on readonly trees

- spec/getSnapshot.spec.ts
- src/snapshot.ts
The snapshot type for a reference should be `string | number`, although we set it as just string in MQT:
But when we have a reference type in a map/array, we currently return the referenced object value itself, not its identifier. If someone then tries to construct an object from this snapshot, 💥.
This adds a special case in our snapshotter for `types.map` and `types.array` to check the children type first. If a reference type, we pull out the identifier, otherwise we do the regular snapshotting of children.
I saw this when doing some testing in Gadget, and got this:
> Ensure we properly snapshot reference types in maps/arrays

- bench/all.ts
I kept existing benchmarks the same name to maintain the historical values.
This should allow us to detect any perf regressions when bumping mobx / mobx-state-tree, and generally have a good comparison between MQT and MST.
> Add some benchmarks to test mobx-state-tree instantiation

- bench/all.ts
- package.json
- pnpm-lock.yaml
- spec/api.spec.ts
- spec/class-model-mixins.spec.ts
- spec/class-model-references.spec.ts
- spec/class-model.spec.ts
- spec/late.spec.ts
- spec/map.spec.ts
- spec/reference.spec.ts
- spec/schemaHash.spec.ts
- spec/union.spec.ts
- src/api.ts
- src/class-model.ts
- src/compose.ts
- src/custom.ts
- src/enumeration.ts
- src/fast-instantiator.ts
- src/model.ts
- src/optional.ts
- src/reference.ts
- src/refinement.ts
- src/simple.ts
- src/snapshot.ts
- src/types.ts
- src/union.ts
I packed a bunch of stuff into one PR, but split it up into separate commits:
* Bumped most dependencies
* Not bumping deep-freeze-es6, which jest is unhappy with for any version >= 2.
* Not bumping eslint, because v9 isn't backwards compatible. Best to wait a few months 
for it to settle and the plugin ecosystem to support v9.
* Fixed any linting issues due to bumping prettier/TS
* We were always checking the `type` argument passed to `ensureRegistered` for registration, and not each part of the prototype chain.
* Increases `initCount` in our benchmarks so that we don't get any unfortunate issues where a benchmark has some JITed and non-JITed samples. Not sure if the value is high enough to ensure things will be JIT-ed, but I figure it's still an improvement.
**TODO**
> Update all dependencies + fix ensureRegistered bug

- package.json
Compare: https://github.com/gadget-inc/mobx-quick-tree/compare/0.6.2...HEAD
Rough outline of changes:
1. `getSnapshot` now properly snapshots reference types in maps/arrays, returning the identifier instead of the referenced model (https://github.com/gadget-inc/mobx-quick-tree/pull/82)
2. Implemented `resolveIdentifier` for readonly nodes (https://github.com/gadget-inc/mobx-quick-tree/pull/79)
3. Bumped to latest version of `typescript`, `mobx-state-tree`, and `mobx`.
> Bump MQT to version 0.7.0

- .github/workflows/benchmark.yml
Upgrading to the v2 of https://github.com/CodSpeedHQ/action will bring a better base run selection algorithm, better logging, and continued support.
> chore(bench): update CodSpeed/action to v2

- src/class-model.ts
- src/fast-getter.ts
- src/fast-instantiator.ts
- src/symbols.ts
This implements a better performing getter function for readonly instances. Before this, we used the same definition of the getter function for all views, which ended up megamorphic, because it accessed a very wide variety of properties for every instance! Instead, this evals a monomorphic getter for each one. I also changed the object that stores the memos to have a fixed shape from birth by evaling it out as well.
I also changed us to use the object itself to store all the memoized values, instead of two other tracker objects. We were previously using the trackers in order to implement memoization of undefined and null correctly. Now, we set up symbol properties to store all the memos, but on the prototype of the class model. This means we don't spend any time setting them up during …
> Faster cached view version 7: values right on the instance

- src/array.ts
Push in a group to avoid the array needing to resize as we push more elements and one less function call
> Improve QuickArray creation performance

- spec/class-model-references.spec.ts
- spec/reference.spec.ts
- src/fast-instantiator.ts
- src/maybe.ts
This fixes a bug in the fast instantiator code where valid references would throw a `can't resolve reference` error due to the instantiation order within MQT. We were accidentally eagerly resolving some references when constructing a tree, where we resolved the reference at reference instantiation time, instead of late resolving them at the very end like we normally do via `context.referenceResolvers`. 
This only happened for wrapped reference types like a `maybe(reference())` or a `late(reference())` because of an instanceof check that failed for wrapped types. Instead, we can use `isReferenceType` from MST to unwrap and answer the real question we are asking.
Fixes https://github.com/gadget-inc/mobx-quick-tree/issues/78, which was an overly broad bug report as it turns out -- class …
> Ensure types.maybe(types.reference()) types are resolved late after construction

- flake.lock
- flake.nix
This upgrades the dev environment for MQT to node v22 from node v21. According to codspeed at least, the v8 upgrade buys at least 10% better performance across the board!
> Run node v22 in dev and CI

- README.md
- spec/__snapshots__/class-model-snapshotted-views.spec.ts.snap
- spec/class-model-mixins.spec.ts
- spec/class-model-snapshotted-views.spec.ts
- spec/class-model.spec.ts
- spec/getSnapshot.spec.ts
- spec/helpers.ts
- src/api.ts
- src/class-model.ts
- src/fast-getter.ts
- src/fast-instantiator.ts
- src/types.ts
This is a subset of #69 that only includes re-hydrating `@snapshottedView`'s from a snapshot. This does not include storing the result of a `@snapshottedView`'s value into a snaphot via `getSnapshot` -- that must be done manually.
Gadget side PR showing how it might be used: https://github.com/gadget-inc/gadget/pull/11994
Below is a revised version of #69's description
---
This adds a feature for caching the output of a view in the snapshot of a node. For expensive views, it's nice to compute them at write time, serialize their return values, and then deserialize them in all the readonly contexts instead of computing them. For things like Gadget's action options (or even the string operations to produce the api identifier), we're already computing them once, we can cache that through the …
> Add snapshottedViews

- spec/class-model-snapshotted-views.spec.ts
- src/class-model.ts
While adding `@snapshottedView` to Gadget, I encountered an issue where the reaction we set up to track `@snapshottedView`s was still running after we detached a model from the tree:
```
[mobx] Encountered an uncaught exception that was thrown by a reaction or observer component, in: 'Reaction[Reaction@998]' Error: [mobx-state-tree] You are trying to read or write to an object that is no longer part of a state tree. (Object type: 'DataModel', Path upon death: '/models/DataModel-xyz', Subpath: 'type', Action: ''). Either detach nodes first, or don't use objects after removing / replacing them in the tree.
```
This PR disposes the reactions after the node is destroyed so we avoid this error.
> Dispose @snapshottedView reactions when destroyed

- README.md
- spec/class-model-snapshotted-views.spec.ts
- src/class-model.ts
This adds `shouldEmitPatchOnChange` to `@snapshottedView`'s options so users can opt of emitting patches when snapshotted views for changes.
Tracking snapshotted views causes them to be immediately computed which isn't ideal if you don't need to track their changes.
> Add shouldTrackChanges option to @snapshottedView

- README.md
- spec/__snapshots__/class-model-snapshotted-views.spec.ts.snap
- spec/class-model-snapshotted-views.spec.ts
- src/class-model.ts
We added `shouldEmitPatchOnChange` in #107, but defaulted it to true.
After starting to use `shouldEmitPatchOnChange` in Gadget, we realized that users should opt-in to emitting patches for snapshotted view changes rather than having to opt-out. This PR fixes that.
This is technically a breaking change but since so few people use mobx-quick-tree and #107 has been released for less than 24h this should be fine.
> Default shouldEmitPatchOnChange to false

- package.json
- spec/reference.spec.ts
- src/array.ts
- src/fast-instantiator.ts
- src/map.ts
- src/reference.ts
MST proper supports an `acceptsUndefined: false` on safe references that automatically prunes invalid references from parent maps and arrays. I wanna use it in Gadget but noticed that it no worky -- we pass the option through to observable instances fine but didn't do anything with it in readonly instances. This adds handling for the special case, which requires arrays and maps to look at the child type, and if it is a safe reference with the option set, omit unresolved entries from the result. Woop woop.
> Add support for acceptsUndefined: false to safe references

- bench/cross-framework.benchmark.ts
- src/class-model.ts
When setting up class models, we had to do a bunch of stuff to allow `this.stuff` to work within a class model view or action function. Class models refer to themselves as a `this` for performance in the read only world, but MST uses closures over `self`. We use `bindToSelf` to forcibly bind all the functions to use `self` for this. 
We don't need to actually do this bind for views however -- mst will execute them with the right `this` kind of by accident! MST defines the views right on the observable object itself, so without any mucking about the `this` is correct. Better yet, we know that the incoming view functions from an MQT class aren't weirdly bound to some other `this` as that doesn't work with MQT in the first place.
Regrettably, we do however need to continue to do this bind …
> Don't re-bind views to this -- MST gives them the right `this` by moving them right onto self
